# Generated by Django 5.0.1 on 2024-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='type',
            field=models.CharField(choices=[('practice', 'Practice'), ('transaction', 'Transaction')], default='practice', max_length=11),
            preserve_default=False,
        ),
    ]
