# Generated by Django 5.0.1 on 2024-08-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('multiple choice', 'Multiple Choice'), ('matching', 'Matching'), ('plan, map, diagram labeling', 'Plan, Map, Diagram Labeling'), ('form, note, table, flow-chart, summary completion', 'Form, Note, Table, Flow-chart, Summary Completion'), ('sentence completion', 'Sentence Completion'), ('short answer questions', 'Short Answer Questions'), ('pick from a list', 'Pick from a list')], max_length=50)),
                ('options', models.JSONField(blank=True, default=dict, null=True)),
                ('correct_answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audios.audios')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
