# Generated by Django 5.0.1 on 2024-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='condition',
            field=models.CharField(default='Choose the correct letters: A, B or C.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
