# Generated by Django 5.0.1 on 2024-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_condition_alter_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(),
        ),
    ]
