# Generated by Django 5.0.1 on 2024-08-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questions_condition_alter_questions_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Question'},
        ),
    ]
